spring.datasource.url=jdbc:postgresql://localhost:5432/senac
spring.datasource.username=postgres
spring.datasource.password=teste

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Faz o data.sql rodar sempre na inicialização
#spring.sql.init.mode=always

#sql nao rodar todas a vezes
spring.sql.init.mode=never

# Garante que as tabelas existam antes de rodar o SQL
spring.jpa.defer-datasource-initialization=true

# Segurança OAuth2
security.client-id=myclientid
security.client-secret=myclientsecret
security.jwt.duration=86400

# CORS
cors.origins=http://localhost:3000,http://localhost:4200